-- 20261006130000_subscription_payments_client_request_key.sql
--
-- REPAIR migration. 20261006110000_payment_idempotency.sql was recorded as applied in
-- supabase_migrations.schema_migrations, but its ALTER TABLE / CREATE INDEX statements were
-- missing from the file that ran: the file had been regenerated by splitting the previous text
-- on the first occurrence of "DROP FUNCTION IF EXISTS public.record_payment_and_renew", and
-- that string also appears inside the file's own ROLLBACK comment - so everything before the
-- DROP (the column, its comment and the unique index) was silently dropped from the file.
--
-- Consequence: record_payment_and_renew was replaced with a body that inserts
-- client_request_id while the column did not exist, so every manual payment recording failed
-- at runtime with "column client_request_id does not exist" (PostgreSQL resolves a plpgsql
-- body's SQL at first execution, not at CREATE time, which is why the migration itself passed).
--
-- This migration adds exactly what 110000 should have. Both files are idempotent
-- (IF NOT EXISTS), so a fresh `supabase db reset` and this already-migrated database converge
-- on the same schema.
--
-- ROLLBACK:
--   DROP INDEX IF EXISTS public.subscription_payments_client_request_key;
--   ALTER TABLE public.subscription_payments DROP COLUMN IF EXISTS client_request_id;

ALTER TABLE public.subscription_payments
  ADD COLUMN IF NOT EXISTS client_request_id uuid;

COMMENT ON COLUMN public.subscription_payments.client_request_id IS
  'Idempotency key of the operator action that recorded this payment (audit T2 #11). Unique per project; NULL for historical rows.';

CREATE UNIQUE INDEX IF NOT EXISTS subscription_payments_client_request_key
  ON public.subscription_payments (project_id, client_request_id)
  WHERE client_request_id IS NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
     WHERE table_schema = 'public' AND table_name = 'subscription_payments'
       AND column_name = 'client_request_id'
  ) THEN
    RAISE EXCEPTION 'assertion failed: client_request_id was not added';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE indexname = 'subscription_payments_client_request_key') THEN
    RAISE EXCEPTION 'assertion failed: the idempotency index was not created';
  END IF;
  -- the function that needs it must still be the 8-arg version
  IF NOT EXISTS (
    SELECT 1 FROM pg_proc
     WHERE proname = 'record_payment_and_renew'
       AND pg_get_function_identity_arguments(oid) LIKE '%p_client_request_id%'
  ) THEN
    RAISE EXCEPTION 'assertion failed: record_payment_and_renew lost its idempotency parameter';
  END IF;
END $$;
